"""Add distance_per_workout column

Revision ID: 0d052e042afe
Revises: 15c36df33ad1
Create Date: 2025-06-21 00:28:25.286838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d052e042afe'
down_revision: Union[str, None] = '15c36df33ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_workouts', sa.Column('distance_per_workout', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_workouts', 'distance_per_workout')
    # ### end Alembic commands ###
