"""add new field to Suggested_workouts

Revision ID: 15c36df33ad1
Revises: 3f38d94d50e9
Create Date: 2025-06-17 16:21:53.839130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c36df33ad1'
down_revision: Union[str, None] = '3f38d94d50e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggested_workouts', sa.Column('focus', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggested_workouts', 'focus')
    # ### end Alembic commands ###
