"""add new field to SuggestedWorkout

Revision ID: 3f38d94d50e9
Revises: 8601dd827f48
Create Date: 2025-06-17 15:06:41.043578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f38d94d50e9'
down_revision: Union[str, None] = '8601dd827f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested_workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('recommended_date', sa.Date(), nullable=True),
    sa.Column('workout_type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('pace', sa.String(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('intensity', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggested_workouts_id'), 'suggested_workouts', ['id'], unique=False)
    op.drop_index('ix_suggested workouts_id', table_name='suggested workouts')
    op.drop_table('suggested workouts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested workouts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recommended_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('workout_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pace', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('goal', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('intensity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='suggested workouts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='suggested workouts_pkey')
    )
    op.create_index('ix_suggested workouts_id', 'suggested workouts', ['id'], unique=False)
    op.drop_index(op.f('ix_suggested_workouts_id'), table_name='suggested_workouts')
    op.drop_table('suggested_workouts')
    # ### end Alembic commands ###
