"""fixing schema

Revision ID: 81cb9f554c5b
Revises: 8ad86e38d119
Create Date: 2025-07-03 15:46:48.274168

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81cb9f554c5b"
down_revision: Union[str, None] = "8ad86e38d119"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uix_user_date', 'daily_entries', ['user_id', 'date'])
    op.drop_column("race_plans", "target_level")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "race_plans",
        sa.Column("target_level", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("uix_user_date", "daily_entries", type_="unique")
    # ### end Alembic commands ###
