"""

Revision ID: 8ad86e38d119
Revises: 30e731455d11
Create Date: 2025-07-03 15:08:01.000429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8ad86e38d119"
down_revision: Union[str, None] = "30e731455d11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uix_user_date', 'daily_entries', ['user_id', 'date'])
    op.add_column("users", sa.Column("target_level", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "target_level")
    op.drop_constraint("uix_user_date", "daily_entries", type_="unique")
    # ### end Alembic commands ###
